In [1]:
import numpy as np
from sage.numerical.mip import MIPSolverException

In [17]:
from sage import matrix

In [2]:
(l1,l2) = var("l1 l2")
assume(l1>=1)
assume(l2>=1)
solve(l1*l2<0, [l1,l2])

[[0 < l2, l1 < 0], [l2 < 0, 0 < l1]]

In [2]:
p1 = Polyhedron(ieqs=[[0,1,-1]])

In [13]:
p = MixedIntegerLinearProgram(maximization=True,solver='ppl')
x = p.new_variable(nonnegative=True)

In [14]:
p.add_constraint(x[0]+x[1] == 0)
p.add_constraint(x[0]+x[1] == 1)
p.add_constraint(x[0] <= 1.1)
p.set_objective(x[0])

In [15]:
p.show()

Maximization:
  x_0 

Constraints:
  constraint_0: 0 <= x_0 + x_1 <= 0
  constraint_1: 1 <= x_0 + x_1 <= 1
  constraint_2: x_0 <= 11/10
Variables:
  x_0 is a continuous variable (min=0, max=+oo)
  x_1 is a continuous variable (min=0, max=+oo)


In [16]:
try:
    p.solve()
except MIPSolverException as err:
    s = str(err)
    if "no feasible solution" in s:
        print("hello")

NameError: name 'MIPSolverException' is not defined

MIPSolverException: PPL : There is no feasible solution

In [127]:
p.get_values(x)

{0: 0, 1: 0}

In [110]:
p.solve()

5

In [107]:
p.base_ring()

Real Double Field

In [85]:
p.get_values(x)

{0: 1.0, 1: -1.0}

In [184]:
p = MixedIntegerLinearProgram(maximization=True, solver='GLPK')
x = p.new_variable(nonnegative= True )
p.set_objective(x[1] + 5*x[2])
p.add_constraint(x[1] + 2/10*x[2], max=4)
p.add_constraint(1.5*x[1]+3*x[2], max=4)
p.set_objective(None)
p.solve()

0.0

In [185]:
p.get_values(x)

{1: 0.0, 2: 0.0}

In [247]:
m = matrix(np.array([[1, 0.2], [1.5, 3]]));
#m = matrix([[1, 0.2], [1.5, 3]])
p = MixedIntegerLinearProgram(maximization=True, solver='ppl')
x = p.new_variable(nonnegative=True)
p.set_objective(x[0])
p.add_constraint(m * x <= [4,3])
p.solve() # rel tol 1e-15

2

In [248]:
p.solve()
p.get_values(x)

{0: 2, 1: 0}

In [2]:
GF(2)

Finite Field of size 2

In [3]:
matrix(ZZ, 2, 3, {(0,0):4})

[4 0 0]
[0 0 0]

In [258]:
C = ChainComplex({0: matrix(ZZ, 2, 3, [3, 0, 0, 0, 0, 0])})

In [260]:
C.betti(1)

1

In [26]:
p = MixedIntegerLinearProgram(maximization=True, solver='GLPK')
x = p.new_variable(nonnegative=True)
p.set_objective(x[1] + 5*x[2])
p.add_constraint(x[1]+x[2], min= 0, max =0)

In [27]:
p.set_objective(None)

In [28]:
try:
    p.solve()
except MIPSolverException as err:
    s = str(err)
    if "no feasible solution" in s:
        print("hello")

In [25]:
np.array([3,4]).tolist()

[3, 4]

In [23]:
m = matrix([[1, 0.2], [1.5, 3]]);
p = MixedIntegerLinearProgram(maximization=True, solver='ppl')
x = p.new_variable(nonnegative=True)
p.set_objective(0)
p.add_constraint(m * x <= np.array([4,3]))
#p.solve() # rel tol 1e-15

TypeError: unable to convert array([4, 3]) to a rational

In [9]:
def solvePLL(m, y):
    
    p = MixedIntegerLinearProgram(maximization=True, solver='ppl')
    x = p.new_variable(nonnegative=True)
    p.set_objective(0)
    p.add_constraint(m * x <= y)
    
    try:
        #print(p.solve())
        return True
    except MIPSolverException as err:
        s = str(err)
        if "no feasible solution" in s:
            return False
        
    return False

In [ ]:
m = matrix([[1, 0.2], [1.5, 3]]).tolist()
y = [3,4]
solvePLL(m,y)

In [4]:
m = matrix([[1, 2], [3, 5]])
y = [3,4]
solvePLL(m,y)

NameError: name 'solvePLL' is not defined

In [16]:
m

[1 2]
[3 5]

In [26]:
a = np.array([[1,2],[1,2]])
np.unique(a,axis = 0)

array([[1, 2]])

In [28]:
a = [[1,2],[1,2]]

In [30]:
np.array([1,2]) - np.array([2,1])

array([-1,  1])

In [8]:
pmatrix  = []
generate_p_matrix([4,4],pmatrix)

In [31]:
pmatrix = np.array(pmatrix)

In [33]:
(pmatrix[0] - pmatrix[1]).tolist()

[0, 0, 0, 0, 0, 0, -1, 1]

In [1]:
from helpersRational import run3rational
run3rational('4_2','42_symmetric.dat','../../../extraRestriction/restrictions21.json')

6 4
6 2
4 0
2 0
1 0
predecessors done
logics done
Hello


In [3]:
(4^^(1<<2))*3

0

In [3]:
Matrix([[1,2],[3,4]])

[1 2]
[3 4]

In [7]:
import numpy as np

In [11]:
matrix(np.array([[1,2],[3,4]])*x)

[  x 2*x]
[3*x 4*x]

In [1]:
from helpersRational import *
run3rational('4_2','42_symmetric.dat','../../../extraRestriction/restrictions21.json')

6 4
6 2
4 0
2 0
1 0
predecessors done
logics done
